config/routes.rb
Rails.application.routes.draw do
  get 'blogs/new'
  get 'sessions/new'

  root 'pages#index'
  get 'pages/help'

  resources :users

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :blogs
  post '/blogs/:id/update',  to: 'blogs#edit'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :user_id, presence: true
  validates :title, presence: true
  validates :content, presence: true
  
  belongs_to :user
  
  mount_uploader :image, ImageUploader
  
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  
  has_secure_password
  
  has_many :blogs
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :info, :warning, :danger

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs= Blog.all
  end
  
  
  def new
    @blog= Blog.new
  end
  
  def create
    @blog= current_user.blogs.new(blog_params)
    if @blog.save
      redirect_to blogs_path, success:"投稿しました"
    else 
      flash.now[:danger]="投稿に失敗しました"
      render :new
    end 
  end
  
  def show
    @blog = Blog.find_by(id: params[:id])
  end
  
  def edit
    @blog = Blog.find_by(id: params[:id])
  end
  
  def update
    @blog= Blog.find_by(id: params[:id])
    if @blog.update(blog_params)
      redirect_to blogs_path, success:"更新しました"
    else
      flash.now[:danger]
      render :edit
    end  
  end
  
  def destroy
    @blog= Blog.find_by(id: params[:id])
    @blog.delete
    redirect_to blogs_path, success: "削除しました"
  end
    
  
  
  private
  def blog_params
    params.require(:blog).permit(:title, :content, :image)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email_params)
    if user && user.authenticate(password_params[:password])
      log_in(user)
      redirect_to root_path, success: 'ログインに成功しました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

 def destroy
    log_out
    redirect_to root_url, info: 'ログアウトしました'
 end

  private
   def email_params
    params.require(:session).permit(:email)
   end
  
  def password_params
    params.require(:session).permit(:password)
  end
  
  
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user= User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
       redirect_to root_path, success: "登録が完了しました"
       
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
      
    end
  end
  
  def show
    @user= current_user
  end
  
  def edit
    @user = User.find_by(id: params[:id])
  end
  
  def update
    @user= User.find_by(id: params[:id])
    if @user.update(blog_params)
      redirect_to blogs_path, success:"更新しました"
    else
      flash.now[:danger]
      render :edit
    end  
  end
  
  def destroy
    @user= User.find_by(id: params[:id])
    @user.delete
    redirect_to blogs_path, success: "削除しました"
  end
  
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
    
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/edit.html.erb
<div class="topic_new_warapper">
  <div class= "container">
    <div class="row">
      <div class= "col-md-6 col-md-offset-3">
        <h1>ブログ編集</h1>
        <%= form_for @blog do |f| %>
          <div class="form-group">
            <%= f.label :image, "画像" %>
            <%= f.file_field :image %>
          </div>
          <div class="form-group">
            <%= f.label :title, "タイトル" %>
            <%= f.text_area :title, class: "form-control" %>
          </div>
          <div class= "form-group">
            <%= f.label :content, "コンテンツ" %>
            <%= f.text_area :content, class: "form-control"%>
          </div>
            <%= f.submit "更新", class: 'btn btn-black btn-block' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/blogs/index.html.erb
<h1>ブログ一覧</h1>

<% @blogs.each do |b|%>
  <%= link_to blog_path(id: b.id) do %>
    <%= b.title %>
  <% end %>
<% end %>

app/views/blogs/new.html.erb
<div class="topic_new_warapper">
  <div class= "container">
    <div class="row">
      <div class= "col-md-6 col-md-offset-3">
        <h1>ブログ新規作成</h1>
        <%= form_for @blog do |f| %>
          <div class="form-group">
            <%= f.label :image, "画像" %>
            <%= f.file_field :image %>
          </div>
          <div class="form-group">
            <%= f.label :title, "タイトル" %>
            <%= f.text_area :title, class: "form-control" %>
          </div>
          <div class= "form-group">
            <%= f.label :content, "コンテンツ" %>
            <%= f.text_area :content, class: "form-control"%>
          </div>
            <%= f.submit "投稿", class: 'btn btn-black btn-block' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/blogs/show.html.erb
<div class="blog-show-wrapper">
  <div class: "show-image">
    <%= image_tag @blog.image.url, class: "image" %>
  </div>
  <div class: "show-title">
    <%= @blog.title%>
  </div>
  <div class: "show-content">
    <%= @blog.content%>
  </div>
    <%= link_to "編集", edit_blog_path %>
     <%= link_to "削除", blog_path, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>

    <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
      <div class="container">
        <%= link_to root_path do %>
          <span><%= "home" %></span>
        <% end %>
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li>
              <%= link_to new_user_path do %>
                <%= "登録" %>
              <% end %>
            </li>
            <li>
              <%= link_to login_path do %>
                <%= "ログイン" %>
              <% end %>
            </li>
            <li>
              <%= link_to logout_path, method: :delete do %>
                <%= "ログアウト" %>
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_path do %>
                <%= "ユーザー編集" %>
              <% end %>  
            </li>    
            <li>
              <%= link_to blogs_new_path do %>
                <%= "ブログ作成" %>
              <% end %>  
            </li>  
            <li>
              <%= link_to blogs_path do %>
                <%= "ブログ一覧" %>
              <% end %>  
            </li>
          <% else %>
            <li>
              <%= link_to new_user_path do %>
                <%= "登録" %>
              <% end %>
            </li>
            <li>
              <%= link_to login_path do %>
                <%= "ログイン" %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <%= yield %>


<script>
  $(function(){
    $(".alert").fadeOut(5000);
  });
</script>

  </body>
</html>

app/views/pages/index.html.erb
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <h1 class="text-white">ブログ作成アプリ</h1>
    <h2 class="text-white">ブログを簡単に作成できます</h2>
    <div class="row">
      <div class="col-md-offset-3 col-md-3">
        <%= link_to '登録', new_user_path, class: 'btn btn-block btn-white' %>
      </div>
      <div class="col-md-3">
        <%= link_to 'ログイン', login_path, class: 'btn btn-block btn-white' %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">登録</h1>
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :name, "お名前", class: 'text-white' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email, "メールアドレス", class: 'text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
           <div class="form-group">
            <%= f.label :password, "パスワード", class: 'text-white' %>
            <%= f.password_field :password, class: 'form-control' %>
           </div>
          <div class="form-group">
            <%= f.label :password_confirmation, "パスワード(確認用)", class: 'text-white' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
          <%= f.submit "登録", class: 'btn-block btn-white' %>
        <% end %>
        <%= link_to 'ログインはこちら', login_path, class: 'text-white' %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="blog-show-wrapper">
  <div class: "show-title">
    <%= @user.name%>
  </div>
  <div class: "show-content">
    <%= @user.email%>
  </div>
    <%= link_to "編集", "#" %>
     <%= link_to "削除", "#" %>
</div>